---
# CatalogSource
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-watson-aimanager-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM Watson AI Manager catalog source
  publisher: IBM
  sourceType: grpc
  image: docker.io/ibmcom/ibm-watson-ai-manager-operator-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
---
# "IBM Watson AIOps AI Manager" operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: aimanager-operator
  namespace: $NAMESPACE_CP4AIOPS
spec:
  channel: v1.0
  installPlanApproval: Automatic
  name: aimanager-operator
  source: ibm-watson-aimanager-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: aimanager-operator.v1.0.0
---
# AIManager instance
apiVersion: ai-manager.watson-aiops.ibm.com/v1beta1
kind: AIManager
metadata:
  name: aimanager
  namespace: $NAMESPACE_CP4AIOPS
spec:
  existingPullSecret:
    name: cp.stg.icr.io
  flink:
    storage:
      enabled: true
      storageClassName: ""  # ReadWriteMany
      storageSize: 1Gi
    taskmanager:
      replicas: 1
      taskmanagerSlots: 12
  size: small
  license:
    accept: true
  zen:
    storage:
      storageClassName: ""
  aimanagerValues:
    postgres:
      keeper:
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      livenessProbe:
        failureThreshold: 5
        initialDelaySeconds: 300
        periodSeconds: 15
        successThreshold: 1
        timeoutSeconds: 15
      readinessProbe:
        failureThreshold: 5
        initialDelaySeconds: 300
        periodSeconds: 15
        successThreshold: 1
        timeoutSeconds: 15
    sentinel:
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
  kafka:
    autoTopicCreation: false
    storage:
      enabled: true
      storageClassName: ""
      storageSize: 5Gi
  repo: ''
  version: 2.1.0
  minio:
    storage:
      storageClassName: ""
      storageSize: 5Gi
      enabled: true
  postgres:
    storage:
      enabled: true
      storageClassName: ""
      storageSize: 5Gi
  storage:
    enabled: true
    storageClassName: "$STORAGECLASS_FILE"
  elasticsearch:
    storage:
      enabled: true
      storageClassName: ""
      storageSize: 5Gi
  modelTrain:
    maxLearners: 2
    pollInterval: 60
    sizeLimit: 1000
