---
# CatalogSource
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-watson-aiops-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM Watson AIOps catalog source
  publisher: IBM
  sourceType: grpc
  image: docker.io/ibmcom/ibm-operator-catalog:latest
  updateStrategy:
    registryPoll:
      interval: 45m
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibm-watson-aiops-operators
  namespace: $NAMESPACE_CP4AIOPS
spec:
  targetNamespaces:
  - $NAMESPACE_CP4AIOPS
---
# "Watson AI Ops" operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-watson-aiops
  namespace: $NAMESPACE_CP4AIOPS
spec:
  channel: v1.1
  installPlanApproval: Automatic
  name: ibm-watson-aiops
  source: ibm-watson-aiops-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-watson-aiops-operator.v1.1.0
