---
# IBM CS Operators
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: opencloud-operators
  namespace: openshift-marketplace
spec:
  displayName: IBM CS Operators
  publisher: IBM
  sourceType: grpc
  image: docker.io/ibmcom/ibm-common-service-catalog:latest
  updateStrategy:
   registryPoll:
     interval: 45m
---
# IBM Licensing Operator
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: ibm-common-services-operators
  namespace: $NAMESPACE_CS
spec:
  targetNamespaces:
  - $NAMESPACE_CS
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-licensing-operator-app
  namespace: $NAMESPACE_CS
spec:
  channel: stable-v1
  installPlanApproval: Automatic
  name: ibm-licensing-operator-app
  source: opencloud-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-licensing-operator.v1.3.1
---
# Strimzi 0.19 operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-kafka-operator
  namespace: openshift-operators
spec:
  channel: strimzi-0.19.x
  installPlanApproval: Automatic
  name: strimzi-kafka-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: strimzi-cluster-operator.v0.19.0
