apiVersion: watson-aiops.ibm.com/v1beta1
kind: NOI
metadata:
  name: noi
  namespace: $NAMESPACE_CP4AIOPS
spec:
  license:
    accept: true
  advanced:
    antiAffinity: false
    imagePullPolicy: IfNotPresent
    imagePullRepository: cp.icr.io/cp/noi
  ldap:
    port: '389'
    mode: standalone
    userFilter: 'uid=%s,ou=users'
    bindDN: 'cn=admin,dc=mycluster,dc=icp'
    sslPort: '636'
    url: 'ldap://localhost:389'
    suffix: 'dc=mycluster,dc=icp'
    groupFilter: 'cn=%s,ou=groups'
    baseDN: 'dc=mycluster,dc=icp'
    storageSize: 1Gi
    serverType: CUSTOM
    storageClass: ''
  backupRestore:
    enableAnalyticsBackups: false
  topology:
    enabled: true
    storageClassElasticTopology: ''
    storageSizeElasticTopology: 5Gi
    storageSizeFileObserver: 5Gi
    storageClassFileObserver: ''
    appDisco:
      enabled: false
      scaleSSS: '1'
      tlsSecret: ''
      dbsecret: ''
      db2database: taddm
      dburl: ''
      certSecret: ''
      db2archuser: archuser
      secure: false
      scaleDS: '1'
      db2user: db2inst1
      dbport: '50000'
    observers:
      docker: false
      taddm: false
      servicenow: false
      ibmcloud: false
      alm: false
      contrail: false
      cienablueplanet: false
      kubernetes: true
      bigfixinventory: false
      junipercso: false
      dns: false
      itnm: false
      ansibleawx: false
      ciscoaci: false
      azure: false
      rancher: false
      newrelic: false
      vmvcenter: false
      rest: false
      appdynamics: false
      jenkins: false
      zabbix: false
      file: false
      googlecloud: false
      dynatrace: false
      aws: false
      openstack: false
      vmwarensx: false
    netDisco: false
  version: 1.6.3
  entitlementSecret: cp.icr.io
  clusterDomain: "$ocp_cluster_domain"
  integrations:
    humio:
      repository: ''
      url: ''
  persistence:
    storageSizeNCOBackup: 5Gi
    enabled: false
    storageSizeNCOPrimary: 5Gi
    storageClassNCOPrimary: ''
    storageSizeImpactServer: 5Gi
    storageClassImpactServer: ''
    storageClassKafka: ''
    storageSizeKafka: 5Gi
    storageClassCassandraBackup: ''
    storageSizeCassandraBackup: 5Gi
    storageClassZookeeper: ''
    storageClassCouchdb: ''
    storageSizeZookeeper: 5Gi
    storageSizeCouchdb: 2Gi
    storageClassCassandraData: ''
    storageSizeCassandraData: 5Gi
    storageClassDB2: ''
    storageClassElastic: ''
    storageSizeDB2: 5Gi
    storageClassImpactGUI: ''
    storageSizeImpactGUI: 5Gi
    storageSizeElastic: 5Gi
    storageClassNCOBackup: ''
  deploymentType: trial
