apiVersion: v1
kind: ServiceAccount
metadata:
  name: humio
  namespace: "$NAMESPACE_HUMIO"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: humio
  namespace: "$NAMESPACE_HUMIO"
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: humio
  namespace: "$NAMESPACE_HUMIO"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: humio
subjects:
- kind: ServiceAccount
  name: humio
  namespace: "$NAMESPACE_HUMIO"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: humio
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: humio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: humio
subjects:
- kind: ServiceAccount
  name: humio
  namespace: "$NAMESPACE_HUMIO"
---
# HumioCluster
apiVersion: core.humio.com/v1alpha1
kind: HumioCluster
metadata:
  name: humio-cluster
  namespace: "$NAMESPACE_HUMIO"
spec:
  humioServiceAccountName: humio
  initServiceAccountName: humio
  authServiceAccountName: humio
  autoRebalancePartitions: true
  tls:
    enabled: false
  dataVolumePersistentVolumeClaimSpecTemplate:
    storageClassName: ibmc-block-gold
    accessModes: [ReadWriteOnce]
    resources:
      requests:
        storage: 10Gi
  environmentVariables:
    - name: "SINGLE_USER_PASSWORD"
      value: "password"
    - name: "HUMIO_JVM_ARGS"
      value: "-Xss2m -Xms256m -Xmx1536m -server -XX:+UseParallelOldGC -XX:+ScavengeBeforeFullGC -XX:+DisableExplicitGC -Dzookeeper.client.secure=false"
    - name: "ZOOKEEPER_URL"
      value: "kafka-cluster-zookeeper-client.humio.svc:2181"
    - name: "KAFKA_SERVERS"
      value: "kafka-cluster-kafka-bootstrap.humio.svc:9092"
---
# HumioRepository
apiVersion: core.humio.com/v1alpha1
kind: HumioRepository
metadata:
  name: humio-repository
  namespace: "$NAMESPACE_HUMIO"
spec:
  managedClusterName: humio-cluster
  name: humio-repository
  description: "Humio Repository"
  retention:
    timeInDays: 10
    ingestSizeInGB: 10
    storageSizeInGB: 10
---
apiVersion: core.humio.com/v1alpha1
kind: HumioParser
metadata:
  name: humio-parser
  namespace: "$NAMESPACE_HUMIO"
spec:
  managedClusterName: humio-cluster
  name: humio-parser
  repositoryName: humio-repository
  parserScript: |
    case {
      kubernetes.pod_name=/fluentbit/
        | /\[(?<@timestamp>[^\]]+)\]/
        | /^(?<@timestamp>.*)\[warn\].*/
        | parseTimestamp(format="yyyy/MM/dd' 'HH:mm:ss", field=@timestamp);
      parseJson();
      * | kvParse()
    }
---
apiVersion: core.humio.com/v1alpha1
kind: HumioIngestToken
metadata:
  name: humio-ingesttoken
  namespace: "$NAMESPACE_HUMIO"
spec:
  managedClusterName: humio-cluster
  name: humio-ingesttoken
  repositoryName: humio-repository
  parserName: humio-parser
  tokenSecretName: humio-ingesttoken-token
