# HumioRepository
apiVersion: core.humio.com/v1alpha1
kind: HumioRepository
metadata:
  name: humio-repository
  namespace: "$NAMESPACE_HUMIO"
spec:
  managedClusterName: humio-cluster
  name: humio-repository
  description: "Humio Repository"
  retention:
    timeInDays: 10
    ingestSizeInGB: 10
    storageSizeInGB: 10
---
# HumioParser
apiVersion: core.humio.com/v1alpha1
kind: HumioParser
metadata:
  name: fluentbit-parser
  namespace: "$NAMESPACE_HUMIO"
spec:
  managedClusterName: humio-cluster
  name: fluentbit-parser
  repositoryName: humio-repository
  parserScript: |
    case {
      kubernetes.pod_name=/fluentbit/
        | /\[(?<@timestamp>[^\]]+)\]/
        | /^(?<@timestamp>.*)\[warn\].*/
        | parseTimestamp(format="yyyy/MM/dd' 'HH:mm:ss", field=@timestamp);
      parseJson();
      * | kvParse()
    }
---
# HumioIngestToken
apiVersion: core.humio.com/v1alpha1
kind: HumioIngestToken
metadata:
  name: fluentbit-ingest-token
  namespace: "$NAMESPACE_HUMIO"
spec:
  managedClusterName: humio-cluster
  name: fluentbit-ingest-token
  repositoryName: humio-repository
  parserName: fluentbit-parser
  tokenSecretName: fluentbit-ingest-token
