# HumioRepository
apiVersion: core.humio.com/v1alpha1
kind: HumioRepository
metadata:
  name: logs
  namespace: "$NAMESPACE_HUMIO"
spec:
  managedClusterName: humio-cluster
  name: logs
  description: "My Repository"
  retention:
    timeInDays: 30
    ingestSizeInGB: 50
    storageSizeInGB: 10
---
# HumioIngestToken
apiVersion: core.humio.com/v1alpha1
kind: HumioIngestToken
metadata:
  name: fluentbit-ingest-token
  namespace: "$NAMESPACE_HUMIO"
spec:
  managedClusterName: humio-cluster
  name: fluentbit-ingest-token
  repositoryName: logs
  tokenSecretName: fluentbit-ingest-token
